name: Update Recent Posts

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in latest personal blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "6"
          feed_list: "https://abhinav.ltd/index.xml"
